import { MoodType } from '../../../models/spotify'

export const moodQueries: Record<MoodType, string[]> = {
  happy: [
    'feel good hits',
    'uplifting pop songs',
    'good vibes playlist',
    'genre:pop',
    'genre:dance',
    'genre:funk',
  ],
  sad: [
    'sad songs',
    'heartbreak playlist',
    'melancholy indie',
    'crying',
    'genre:indie',
    'genre:alternative',
    'genre:folk',
    'genre:pop',
  ],
  relaxed: [
    'peaceful music',
    'calm acoustic',
    'meditation sounds',
    'genre:ambient',
    'genre:acoustic',
  ],
  energetic: [
    'workout playlist',
    'high energy dance',
    'pump up songs',
    'genre:electronic',
    'genre:house',
  ],
  angry: [
    'aggressive rock',
    'heavy metal hits',
    'intense music',
    'genre:rock',
    'genre:metal',
    'genre:punk',
  ],
  dreamy: [
    'ethereal soundscapes',
    'dream pop',
    'atmospheric indie',
    'genre:dream-pop',
    'genre:shoegaze',
  ],
  romantic: [
    'love ballads',
    'romantic dinner music',
    'couples playlist',
    'love songs',
    'genre:r-n-b',
    'genre:soul',
    'genre:jazz',
    'genre:pop',
  ],
  party: [
    'dance floor hits',
    'club bangers',
    'party anthems',
    'genre:dance',
    'genre:hip-hop',
    'genre:pop',
  ],
  focused: [
    'study music',
    'concentration playlist',
    'ambient focus',
    'genre:instrumental',
    'genre:classical',
  ],
  chill: [
    'lo-fi beats',
    'sunday morning vibes',
    'coffee shop music',
    'genre:lo-fi',
    'genre:chillout',
    'genre:downtempo',
  ],
}
